### ISSUE TITLE
Please update overlay still appearing

### ISSUE THREAD

**Issue by albertoxamin** [lolPants/faceapp.js#12]

**Comment by albertoxamin** [comment]
I decompiled the latest apk and found this 
![image](https://user-images.githubusercontent.com/6067659/48914889-02cb4a00-ee7d-11e8-82d9-05eabbbeba7d.jpeg)
![image](https://user-images.githubusercontent.com/6067659/48914906-0e1e7580-ee7d-11e8-9900-a03251901b2a.jpeg)

**Comment by luludotdev** [comment]
I don't have access to a rooted phone to packet sniff the logic, if anyone can get the exact URLs used then that'd be appreciated.

As it stands I don't have time or resources to update this myself.

**Comment by ghost** [comment]
What'd you use to decompile?

**Comment by albertoxamin** [comment]
@AndreiG6 I unzipped the apk and used https://github.com/pxb1988/dex2jar to get a jar then https://github.com/java-decompiler/jd-gui to explore the java code.
But the latest Android Studio does this out of the box.

**Comment by albertoxamin** [comment]
I found an implementation which uses the latest api successfully 
https://github.com/reuke/FaceAppDesktop/blob/master/gui/FaceAppApi/V3/APIClient.cs
