### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Too Many Requests

### ISSUE THREAD

**Issue by axelerod12** [lolPants/faceapp.js#6]
All good until you start having lots of calls. Then it stops responding

**Comment by Harsh-Gupta** [comment]
I am also getting too many requests. After multiple requests to FACEAPP api.  Have you got any solution to this? 

Is any any barrier to number of requests per hour or something like that?

**Comment by luludotdev** [comment]
As far as I can tell you can process 50 images every 10 minutes.
This is implemented on their servers and there is nothing that this library can do to work around it.

**Comment by axelerod12** [comment]
Some sites in my niche have found a way
Example:
https://en.nametests.com/test/what-would-you-look-like-as-a-bald-person/30984/

This is a site with millions of visits and they have lots of tests using FaceApp API and they do not seem to have this issue.
How did they do it? Do they have some kind of official partnership with FaceApp?

**Comment by luludotdev** [comment]
`faceapp.js` is an unofficial reverse-engineering of the way the mobile clients work, so they're subject to any of their limitations.

I would assume that the site linked probably have a more official implementation from the company themselves. It also seems that the rate limits are a recent addition as I've only started getting told about it being a problem in the last couple weeks or so.

I don't have any plan to attempt to get around them as that would be breaking their terms of service. You may do so at your own risk.
