### ISSUE TITLE
Client error

### ISSUE THREAD

**Issue by nthanhhai783** [lolPants/faceapp.js#7]
We have created a small application for this effect of faceapp, we follow this project but when we connect the error 
 Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `POST https://node-03.faceapp.io/api/v2.6/photos` resulted in a `429 Too Many Requests` response: {"err":{"detail":"{'desc': 'Too many requests from your IP', 'code': 'too_many_requests'}"}} ' 

How to fix it

**Comment by luludotdev** [comment]
Doing some tests with the the serverside code, it looks like you can use the `process` function 50 times in a ten minute window before it starts to ratelimit you (100 requests but `process` uses two requests per call)

There's nothing I can do from my module other than make people aware that this is happening and encourage them to implement the handling code on their end.
