### ISSUE TITLE
Can't use module.

### ISSUE THREAD

**Issue by braguettop** [lolPants/faceapp.js#9]
I can't use the module, I tried using buffers, path and nothing!
Everytime that I try to use that, gives SyntaxError: Unexpected identifier! Thank you.

![image](https://user-images.githubusercontent.com/38165895/39368989-78784138-4a11-11e8-86a1-508a88f00aac.png)

I removed the `await` and the image was saved, but the image can't be open.
```const faceapp = require('faceapp');
const fs = require('fs');
let image = faceapp.process('./MASAHIRO.jpeg', 'smile_2')
fs.writeFile('face.jpeg', image, 'binary', function(err){
            if (err) throw err
            console.log('File saved.')
        })

**Comment by luludotdev** [comment]
What version of Node.js are you running?
Are you using an async function?
